In [36]:
# Import dependencies 
import pandas as pd
from pathlib import Path
import matplotlib.pyplot as plt
import seaborn as sns
import numpy as np
from sklearn.linear_model import LogisticRegression
from sklearn.preprocessing import StandardScaler
from sqlalchemy import create_engine
from sklearn.preprocessing import LabelEncoder
from sklearn.preprocessing import OneHotEncoder
from sklearn.metrics import classification_report, confusion_matrix

In [37]:
password = input()

postgres


In [38]:
df = pd.read_sql('full_moon_vs_crime_date', f'postgresql://postgres:{password}@hoobaskanks.cem6bfyajguw.us-east-2.rds.amazonaws.com:5432/Horrorscopes')  
df.head()

Sign Crime_Type Crime_Moon_Date
0  Capricorn      THEFT      2009-01-11
1  Capricorn      THEFT      2009-01-11
2  Capricorn      THEFT      2009-01-11
3  Capricorn      THEFT      2009-01-11
4  Capricorn      THEFT      2009-01-11

In [39]:
# Check the shape of the dataframe
print("shape of dataframe is : ", df.shape)
# summary of data
df.info()
#Get Statistical details of data
df.describe()

shape of dataframe is :  (4152, 3)
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 4152 entries, 0 to 4151
Data columns (total 3 columns):
 #   Column           Non-Null Count  Dtype         
---  ------           --------------  -----         
 0   Sign             4152 non-null   object        
 1   Crime_Type       4152 non-null   object        
 2   Crime_Moon_Date  4152 non-null   datetime64[ns]
dtypes: datetime64[ns](1), object(2)
memory usage: 97.4+ KB


/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:6: FutureWarning: Treating datetime data as categorical rather than numeric in `.describe` is deprecated and will be removed in a future version of pandas. Specify `datetime_is_numeric=True` to silence this warning and adopt the future behavior now.
  


Sign Crime_Type      Crime_Moon_Date
count        4152       4152                 4152
unique         12          3                   13
top     Capricorn      THEFT  2009-09-04 00:00:00
freq          457       2158                  411
first         NaN        NaN  2009-01-11 00:00:00
last          NaN        NaN  2009-12-31 00:00:00

In [40]:
# Remove the unncecessary columns
df.drop(columns=["Crime_Moon_Date"], inplace=True)
df.head()

Sign Crime_Type
0  Capricorn      THEFT
1  Capricorn      THEFT
2  Capricorn      THEFT
3  Capricorn      THEFT
4  Capricorn      THEFT

In [41]:
# Encode the Sign column
from sklearn.preprocessing import LabelEncoder
le = LabelEncoder()
df.Sign = le.fit_transform(df.Sign)
df.head

<bound method NDFrame.head of       Sign Crime_Type
0        3      THEFT
1        3      THEFT
2        3      THEFT
3        3      THEFT
4        3      THEFT
...    ...        ...
4147     3      THEFT
4148     3      THEFT
4149     3      THEFT
4150     3      THEFT
4151     3      THEFT

[4152 rows x 2 columns]>

In [42]:
# Encode the Crime_Type column using OneHotEncoder
ohe = OneHotEncoder()
transformed = ohe.fit_transform(df[['Crime_Type']])
print(transformed.toarray())

[[0. 1. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 ...
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 1. 0.]]


/usr/local/lib/python3.7/dist-packages/sklearn/utils/validation.py:1692: FutureWarning: Feature names only support names that are all strings. Got feature names with dtypes: ['quoted_name']. An error will be raised in 1.2.
  FutureWarning,
/usr/local/lib/python3.7/dist-packages/sklearn/utils/validation.py:1692: FutureWarning: Feature names only support names that are all strings. Got feature names with dtypes: ['quoted_name']. An error will be raised in 1.2.
  FutureWarning,


In [43]:
print(ohe.categories_)

[array(['MISCONDUCT', 'THEFT', 'Violent'], dtype=object)]


In [44]:
transformed_df = pd.DataFrame(transformed.toarray())

In [45]:
# Create a new DataFrame from the new encoded columns
df.join(transformed_df)

Sign Crime_Type    0    1    2
0        3      THEFT  0.0  1.0  0.0
1        3      THEFT  0.0  1.0  0.0
2        3      THEFT  0.0  1.0  0.0
3        3      THEFT  0.0  1.0  0.0
4        3      THEFT  0.0  1.0  0.0
...    ...        ...  ...  ...  ...
4147     3      THEFT  0.0  1.0  0.0
4148     3      THEFT  0.0  1.0  0.0
4149     3      THEFT  0.0  1.0  0.0
4150     3      THEFT  0.0  1.0  0.0
4151     3      THEFT  0.0  1.0  0.0

[4152 rows x 5 columns]

In [46]:
df_crime = df.join(transformed_df)
df_crime

Sign Crime_Type    0    1    2
0        3      THEFT  0.0  1.0  0.0
1        3      THEFT  0.0  1.0  0.0
2        3      THEFT  0.0  1.0  0.0
3        3      THEFT  0.0  1.0  0.0
4        3      THEFT  0.0  1.0  0.0
...    ...        ...  ...  ...  ...
4147     3      THEFT  0.0  1.0  0.0
4148     3      THEFT  0.0  1.0  0.0
4149     3      THEFT  0.0  1.0  0.0
4150     3      THEFT  0.0  1.0  0.0
4151     3      THEFT  0.0  1.0  0.0

[4152 rows x 5 columns]

In [47]:
# Rename the Encoded Crime_Type columns
df_crime.rename(columns={0: 'Misconduct', 1: 'Theft', 2: 'Violent'}, inplace=True)
df_crime

Sign Crime_Type  Misconduct  Theft  Violent
0        3      THEFT         0.0    1.0      0.0
1        3      THEFT         0.0    1.0      0.0
2        3      THEFT         0.0    1.0      0.0
3        3      THEFT         0.0    1.0      0.0
4        3      THEFT         0.0    1.0      0.0
...    ...        ...         ...    ...      ...
4147     3      THEFT         0.0    1.0      0.0
4148     3      THEFT         0.0    1.0      0.0
4149     3      THEFT         0.0    1.0      0.0
4150     3      THEFT         0.0    1.0      0.0
4151     3      THEFT         0.0    1.0      0.0

[4152 rows x 5 columns]

In [48]:
df_crime.drop(columns=["Crime_Type"], inplace=True)
df_crime.head()

Sign  Misconduct  Theft  Violent
0     3         0.0    1.0      0.0
1     3         0.0    1.0      0.0
2     3         0.0    1.0      0.0
3     3         0.0    1.0      0.0
4     3         0.0    1.0      0.0

In [49]:
from sklearn.model_selection import train_test_split
#split data into dependent variables(X) and independent variable(y) that we would predict
y = df_crime.pop("Sign")
X = df_crime
#Let’s split X and y using Train test split
X_train,X_test,y_train,y_test = train_test_split(X,y,random_state=1,train_size=0.7)
#get shape of train and test data
print("train size X : ",X_train.shape)
print("train size y : ",y_train.shape)
print("test size X : ",X_test.shape)
print("test size y : ",y_test.shape)

train size X :  (2906, 3)
train size y :  (2906,)
test size X :  (1246, 3)
test size y :  (1246,)


In [50]:
# Standardize the data to treat all features equally
scaler = StandardScaler()
df_crime = scaler.fit_transform(df_crime)

In [51]:
model = LogisticRegression()

In [52]:
# Train the model using the Training data
model.fit(X_train, y_train)

LogisticRegression()

In [53]:
# Make predictions
y_pred = model.predict(X_test)
print(y_pred)

[ 3 11 11 ... 11 11  3]


In [54]:
from sklearn.metrics import accuracy_score
print(accuracy_score(y_test, y_pred))

0.10112359550561797


In [20]:
from sklearn.metrics  import confusion_matrix, classification_report
matrix = confusion_matrix(y_test, y_pred)
print(matrix)

[[ 0  0  0 42  0  0  0  0  0  0  0 41]
 [ 0  0  0 49  0  0  0  0  0  0  0 68]
 [ 0  0  0 34  0  0  0  0  0  0  0 44]
 [ 0  0  0 61  0  0  0  0  0  0  0 64]
 [ 0  0  0 73  0  0  0  0  0  0  0 45]
 [ 0  0  0 50  0  0  0  0  0  0  0 57]
 [ 0  0  0 47  0  0  0  0  0  0  0 48]
 [ 0  0  0 46  0  0  0  0  0  0  0 50]
 [ 0  0  0 41  0  0  0  0  0  0  0 65]
 [ 0  0  0 27  0  0  0  0  0  0  0 58]
 [ 0  0  0 53  0  0  0  0  0  0  0 50]
 [ 0  0  0 68  0  0  0  0  0  0  0 65]]


In [21]:
report = classification_report(y_test, y_pred)
print(report)

              precision    recall  f1-score   support

           0       0.00      0.00      0.00        83
           1       0.00      0.00      0.00       117
           2       0.00      0.00      0.00        78
           3       0.10      0.49      0.17       125
           4       0.00      0.00      0.00       118
           5       0.00      0.00      0.00       107
           6       0.00      0.00      0.00        95
           7       0.00      0.00      0.00        96
           8       0.00      0.00      0.00       106
           9       0.00      0.00      0.00        85
          10       0.00      0.00      0.00       103
          11       0.10      0.49      0.16       133

    accuracy                           0.10      1246
   macro avg       0.02      0.08      0.03      1246
weighted avg       0.02      0.10      0.03      1246



/usr/local/lib/python3.7/dist-packages/sklearn/metrics/_classification.py:1318: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
/usr/local/lib/python3.7/dist-packages/sklearn/metrics/_classification.py:1318: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
/usr/local/lib/python3.7/dist-packages/sklearn/metrics/_classification.py:1318: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
